version: '3'

volumes:
  data_volume:

services:

  app:
    image: my_fin:latest
    container_name: app_main.mf
    build:
      context: .
      dockerfile: cmd/Dockerfile
    restart: always
    depends_on:
      - dbMysql
    command: ["/app/wait-for-it.sh", "db:3303", "--", "/app/my_fin"]

  dbMysql:
    image: mariadb
    env_file:
      - configs/common.env
    container_name: dbMysql.mf
    restart: always
    tty: true
    ports:
      - 3309:3306
    volumes:
      - data_volume:/var/lib/mysql/

  webserver:
    image: nginx:alpine
    container_name: webserver.mf
    restart: always
    tty: true
    volumes:
      - ./configs/nginx_dev:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
