version: '3'

volumes:
  data_volume:

services:

  app:
    image: my_fin:latest
    container_name: app_main.mf
    build:
      context: .
      dockerfile: cmd/Dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - dbMysql
    networks:
      - app-network
    command: ["/app/wait-for-it.sh", "dbMysql:3309", "--", "/app/my_fin"]

  dbMysql:
    image: mariadb
    env_file:
      - configs/common.env
    container_name: dbMysql.mf
    restart: always
    tty: true
    ports:
      - 3309:3306
    volumes:
      - data_volume:/var/lib/mysql/
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge